### PR TITLE
Update PianoRoll.h

### PR DESCRIPTION
**Pull request by musikBear**
This is only an addition of a prototype for new methods in piano-roll.cpp
The additions to piano-roll.cpp is in own commit (not sure if both could be in same commit

### CODE REVIEW

**Comment by musikBear** [comment]
Should a pull request be closed when i select **Merge**?!
This one shows Closed, and it prompt me to **delete** my branch?!
Those steps would imo logically only be done **AFTER** the commit has been _reviewed and accepted_?!?
I find gitHup chokingly unlogical 👎

**Comment by allejok96** [comment]
I'm sorry to say, the reason it was so easy to make this Pull request is that you made the request to yourself. As you can see, your PR is not in [the list of official PRs](https://github.com/LMMS/lmms/pulls). To make make a PR to the official LMMS repository: first select your branch, then click Contribute.

bild

When you do this you will experience more problems. You can try it just to see what happens. But I warn you right now: you will have to clean up you repository. I can give you some tips if you want. It will be lot of work. But you will only need to do it one time. If you learn how to work with github the right way, this won't happen any more in the future.

**Comment by allejok96** [comment]
## This an example of the git workflow
bild

## This is what I *think* you have done
bild

**Comment by musikBear** [comment]
> I'm sorry to say, the reason it was so easy to make this Pull request is that you made the request to yourself. As you can see, your PR is not in [the list of official PRs](https://github.com/LMMS/lmms/pulls). To make make a PR to the official LMMS repository: first select your branch, then click Contribute.
> 
> bild
> 
> When you do this you will experience more problems. You can try it just to see what happens. But I warn you right now: you will have to clean up you repository. I can give you some tips if you want. It will be lot of work. But you will only need to do it one time. If you learn how to work with github the right way, this won't happen any more in the future.

Yeeeeaa..
It ..is
And that despite i _distinctly_ selected **Master** as the base. 
Git set it to _My_ 'Master'.
Why oh why
Where would that workflow be needed?!?
I do feel i need to make one more rant, maybe against myself, but nwm, here it comes:
From _all_ i have read, In computing there is one thing that should be avoided : 

**Identical naming-schemes for different content**

Despite that cardinal-rule, Github not only allows using **Master** for actual **Master** _and_ local 'Master' _and_ own-github-repo-'Master'.
'Master' exists in 3 different versions for one user, and n different versions if collaborators are counted in..
I simply detest this!
Am i wrong..?
Honestly, i have used considerable more time with github meh, than i have with coding.
YES! I should NEVER have made more code locally, than what i should have in ONE PR!
There is my mistake. MY mistake
Mine Mine alone -I did it, It was ME.. I am to blame..
I know that. (I does not help, that the code is behind a VM wall....btw...)
But..
Some type of 'escape' from that blunder...
Just a blarmy pommel-horse for the dirt i dig out in the tunnel (movie-ref..)
NoOoo zip ⚰
But now i have a new idea 🤪 : MSVS2022 and its git integration..

Sorry for wasting your and anyone else's time!

**Comment by allejok96** [comment]
No don't worry, this happens to everyone. Git *is* very difficult and confusing. You don't have to apologize. If didn't want to help you I wouldn't have responded.

Btw I use the git integration of Qt Creator. It makes it easy to switch between patches. And to make commits I use the built in `git gui`. It is not so beautiful but it works. Only when things go wrong is the git command line needed :face_with_spiral_eyes:

**Comment by musikBear** [comment]
> No don't worry, this happens to everyone. Git _is_ very difficult and confusing. You don't have to apologize. If didn't want to help you I wouldn't have responded.
> 
> Btw I use the git integration of Qt Creator. It makes it easy to switch between patches. And to make commits I use the built in `git gui`. It is not so beautiful but it works. Only when things go wrong is the git command line needed 😵‍💫

Thanks! I will see how MSVS fairs -After all MS now own github, so their integration should be if not flawless, then at least 'useable' 🤞

**Pull request merged**
